apiVersion: 1

datasources:
  # Prometheus — источник метрик
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    jsonData:
      httpMethod: POST
      timeInterval: '10s'

  # Tempo — источник трейсов
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    jsonData:
      # Связываем трейсы с метриками Prometheus
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
      # Включаем поиск трейсов
      search:
        hide: false
      nodeGraph:
        enabled: true